### ISSUE TITLE
##[error]Unable to find workflow

### ISSUE THREAD

**Issue by ycnmhd** [benc-uk/workflow-dispatch#1]
I'm triying to use this action on a **private** repo, and I'm getting the following error

Run benc-uk/workflow-dispatch@v1
##[error]Unable to find workflow named 'build_next' in ycnmhd/*** 😥

**Comment by benc-uk** [comment]
Let me test this with private repos and get back to you

**Comment by benc-uk** [comment]
I've just set up a private repo, and was able to trigger a workflow in it just fine
Can you check the token you are using is NOT the github.token and it has write rights to the repo

**Comment by Shamazo** [comment]
I am also experiencing this issue. It cannot find the workflow, I tried with and without setting the ref to the branch I am working in, where the workflow is also defined.

**Comment by benc-uk** [comment]
Are you using the workflow name, i.e. what is in the YAML file, e.g. `name: My Workflow` ?

This is what you should use, not the filename

**Comment by Shamazo** [comment]
I was using the workflow name as defined in the YAML file. Unfortunately it is  private repo or I would share the example with you.

**Comment by benc-uk** [comment]
If you create a secret named `ACTIONS_STEP_DEBUG` and set it to true, you should see the output of the API which lists the workflows in the repo, this should help shed some light on the matter

or call this and see if the named workflow is listed there

```bash
curl https://api.github.com/repos/{{owner}}/{{repo}}/actions/workflows -H "Authorization: Basic {{username}}:{{pat-token}}"
```

**Comment by ycnmhd** [comment]
using a token with the **repo** scope seems to fix the issue for me 😄 ![image](https://user-images.githubusercontent.com/33285087/87356397-4860ed00-c562-11ea-8bdd-29c6c47de138.png)

**Comment by benc-uk** [comment]
Thanks @ycnmhd starting to wonder what the problem might be!  
I don't know the specific permissions to give the token at this point without a fair bit of trial an error ¯\_(ツ)_/¯

**Comment by Shamazo** [comment]
On my end it looks like a possible issue with my repo. When using curl to access the list workflows API I get a not found for my repo, but the list of workflows for this repo. My access key also has repo scope.

**Comment by Shamazo** [comment]
I somewhat fixed it, I ran the workflow I was trying to run via dispatch by making it run on push once, this seems to have 'registered' it. The action now finds the workflow and returns a 204 status, but the workflow does not run.

**Comment by ycnmhd** [comment]
@Shamazo does your target workflow have **on: workflow_dispatch** event? (as suggested [here](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event))

(unrelated) as for the curl command, this authorization header format worked with me 
curl https://api.github.com/repos/{{owner}}/{{repo}}/actions/workflows -H "Authorization: token {{pat-token}}"

**Comment by benc-uk** [comment]
Thanks @ycnmhd, good spot on the Authorization header, basic auth works on public repos, but for private you have to specify Token (which also works on public) or you get a 404. It's a bit inconsistent but this is a very new API for GitHub so maybe needs some work

**Comment by Shamazo** [comment]
My target workflow looks like this:
![image](https://user-images.githubusercontent.com/5744542/87481485-6891ba00-c5fd-11ea-8a3d-f9480c8de5d5.png)

**Comment by eerichmond** [comment]
For me, I encountered this error on a monorepo. Over time the monorepo had accumulated over 30 new or renamed workflows. I added PR #3 to add paging to the list workflows request.

**Comment by blimmer** [comment]
For me, this issue was because the PAT I created (associated with a "bot" user) didn't have write access to the repo. After I added it, I could trigger the workflow.
