### ISSUE TITLE
##[error]No ref found for: refs/pull/67/merge

### ISSUE THREAD

**Issue by dmacusb2** [benc-uk/workflow-dispatch#2]
Hello, thanks for this action!  I am trying to use your action to call a build/test workflow on pull requests.  I have workflow A which runs on pull requests and calls your action to trigger workflow B which runs the build and test.  I have tested workflow B using the built in GitHub UI from the actions page.  When I attempt to trigger workflow B using your action in workflow A I get the error:

```
Workflow id is: 1965986
##[error]No ref found for: refs/pull/67/merge
##[debug]Node Action run completed with exit code 1
```

I have tried passing in `ref: ${{ github.sha }}`, `ref: ${{ github.ref }}`, and omitting `ref` as arguments to your action. I get the same result in all cases. Any ideas what is happening? 

As a final question, I would like to gate my pull request on whether or not the triggered workflow B completes successfully, is that possible?

**Comment by benc-uk** [comment]
I found a thread on this here: https://github.com/actions/checkout/issues/61  
From that I discovered the secret is to use `${{ github.event.pull_request.head.ref }}` as the ref input, I've tested this and it seems to work.

For your second point, I don't think that's going to be possible, the workflow dispatch is asynchronous so there's no way for the calling workflow to know if the target completed successfully or not.  
I suggest combining them into a single workflow and using conditions like `if: github.event_name == 'push'` or other logic, to only run certain steps if the PR completes (and merges into master), for example https://github.com/benc-uk/dapr-store/blob/master/.github/workflows/ci-build.yml

**Comment by dmacusb2** [comment]
Thanks for the reply.  One the second approach I was thinking something like:

- Call the workflow_dispatch to start the new workflow, get back some sort of handle to the new workflow
- Create a new status check on the pr that watches for the new workflow to complete using the handle

**Comment by adadkins** [comment]
@dmacusb2 

One possibility is to pass the commit sha to your dispatch. Then you can have the action run on the commit. 

There are other actions that wait on Commit status. Check out 

uses: "WyriHaximus/github-action-wait-for-status@v1.2"

So your next step can use that action to wait for the dispatch status to finish.

**Comment by CWSites** [comment]
@dmacusb2 https://github.com/lewagon/wait-on-check-action should work for what you're wanting to do.
