### ISSUE TITLE
Changing 'triggered by' username to user who committed

### ISSUE THREAD

**Issue by osbash** [benc-uk/workflow-dispatch#28]
This is more of a question than an issue.

We have this up and running to run a workflow from a different repository perfectly.

In the second repository, we have a second action that triggers a slack notification after the repo is deployed.

Since we have to use personal access tokens with workflow-dispatch, it always includes that user in the slack notification.  Is there a way to configure this to use the github username of the person who actually triggered the original workflow?

For example, workflow-dispatch is configured using a PAT from User A

User B commits and it triggers the actions to begin, but it always says manually run by User A
When the second repo is dispatched, that one also says manually triggered by User A

**Comment by benc-uk** [comment]
I don't think I can affect this, it's how the GitHub API works
