### ISSUE TITLE
Not triggering workflow

### ISSUE THREAD

**Issue by andersson09** [benc-uk/workflow-dispatch#32]
Hi,

So I tried triggering workflow_dispatch manually using the REST API and it works fine. However when using the same curl from a github action the response is fine but the workflow is not trigger, nothing happens. So I tried your github action instead and again it's giving successful 204 yet still not triggering.

Thanks

**Comment by Xplouder** [comment]
I was having the same problem until i created my own PAT as described [here](https://github.com/benc-uk/workflow-dispatch#token). Now its working fine.
