### ISSUE TITLE
Log a Warning/Annotation When a Workflow is Disabled and Pass The Step

### ISSUE THREAD

**Issue by StephenMP** [benc-uk/workflow-dispatch#35]
The current behavior of the action when a workflow being triggered is disabled is to fail the step, and thus fail the action. I feel it would be better, instead, to pass the step and log out a warning/annotation to state that the workflow being called is disabled.

There are instances where we may intentionally disable a workflow, but we will want to see the calling workflow pass (essentially to signify that yes, what you are doing in Workflow A is correct, it's just that Workflow B is disabled).

**Comment by benc-uk** [comment]
Good idea
I've enabled this in `v1.2.1` and `v1`
