### ISSUE TITLE
Run workflows in a specific order

### ISSUE THREAD

**Issue by dreamwhite** [benc-uk/workflow-dispatch#42]
I have three workflows that must run after each other.

e.g. A,B,C must be run in this specific order: A->B->C.

What I see is that your GH action only runs the command "run the workflow" but doesn't wait till each one finishes.
Is there anything I can do to achieve it?

Many thanks

**Comment by benc-uk** [comment]
This is not something that can easily be done via the GitHub API

**Comment by dreamwhite** [comment]
> This is not something that can easily be done via the GitHub API

Ouch, I made some tests after opening this issue and what I wanted to accomplish apparently seems working ([ref](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/.github/workflows/main.yml))
