### ISSUE TITLE
Please move v1 tag

### ISSUE THREAD

**Issue by AlekSi** [benc-uk/workflow-dispatch#6]
The best practice for GitHub Actions versioning is to have SemVer tags like `v1.1.0` for each release and floating tag `v1` for the major version: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#using-tags-for-release-management

Please move the v1 tag to point to the latest release.

**Comment by benc-uk** [comment]
Good catch, I wasn't aware of this recommendation.
I've repointed the v1 tag and created a v1.1.0 full semver tag also

**Comment by AlekSi** [comment]
Thank you!
