### ISSUE TITLE
Support for Node.js 20

### ISSUE THREAD

**Issue by a1ecbr0wn** [benc-uk/workflow-dispatch#67]
I am now getting the following warning with this action when I try to use it.
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: benc-uk/workflow-dispatch@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by grzegorzkrukowski** [comment]
Is there any chance to merge this one soon?

**Comment by mara004** [comment]
@benc-uk ping

**Comment by tylerohlsen** [comment]
GitHub [announced](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) today that Node20 will be enforced on May 13.

**Comment by a1ecbr0wn** [comment]
OK, this is clearly another abandoned GitHub action (there seem to be too many) does anyone have any ideas about alternative actions?

**Comment by grzegorzkrukowski** [comment]
I think we can just maybe fork this one and update it

**Comment by mara004** [comment]
Hmm, after actually reading the announcement, it sounds to me as if node16 actions would just implicitly be migrated to node20, and might as well continue working without further interaction? Or is that understanding incorrect?

**Comment by a1ecbr0wn** [comment]
> Hmm, after actually reading the announcement, it sounds to me as if node16 actions would just implicitly be migrated to node20, and might as well continue working without further interaction? Or is that understanding incorrect?

you might be right, yes

**Comment by mjhipp** [comment]
> OK, this is clearly another abandoned GitHub action (there seem to be too many) does anyone have any ideas about alternative actions?

In updating for Node 20 I have run into a few of these. One I found was archived and left a note in their README that recommended using a `gh cli` step rather than their marketplace action. 

I plan to do that for this one as well. It is a relatively simple step. Here using the input names from this [workflow spec](https://github.com/benc-uk/workflow-dispatch/blob/master/action.yaml) (inside <>):

```yaml
    steps:
      - name: Workflow Dispatch
        run: echo "<inputs>" | gh workflow run <workflow> --json --ref <ref> --repo <repo>
        env:
          GH_TOKEN: <token> # if using outside repo
```

There is also the option of using other methods of input rather than json.

**Comment by benc-uk** [comment]
Not abandoned, just life getting in the way 😞

Just pushed a new version v1.2.3 and the v1 and v1.2 tags should also pick this up

Sorry everyone!

**Comment by a1ecbr0wn** [comment]
Thank you Ben 👍🏼
