### ISSUE TITLE
Error: No ref found for: refs/pull/****/merge

### ISSUE THREAD

**Issue by petja-laitila** [benc-uk/workflow-dispatch#9]
I'm trying to use this action with pull request to queue some workflows, but it seems it doesn't give right commit ref to workflow it dispatches to when using in PR. Should it be the same merge commit actions/checkout@v2 does for pull requests? Can this be done as this action is right now?

**Comment by petja-laitila** [comment]
Sorry, I think this is not something that can be done in this action. Closing.

**Comment by benc-uk** [comment]
Did you try this ?

"If you want to trigger on pull requests and run the target workflow in the context of the pull request branch, set the ref to `${{ github.event.pull_request.head.ref }}`"

This is from the readme

**Comment by petja-laitila** [comment]
I did, but it doesn't work when wanting to test the merge to PR base.

**Comment by CWSites** [comment]
@benc-uk I also tried this with your suggestion and I got the following error. Not sure if it matters or not but I'm trying to merge `master` > `develop` since I have been applying workflow changes directly to master.

```
Run benc-uk/workflow-dispatch@v1
  with:
    inputs: { "ref": "master", "sha": "7bca7c5d3c7c8e78bc5920efb1cf7802902c59e3"}
    token: ***
    workflow: Lint, Test & Build
Workflow id is: 8600649
Error: No ref found for: refs/pull/547/merge
```
